Remove "sex" and "sexual"
meower-media-co/Meower-Server pull request #128
Opened 2022-11-30 03:00 UTC by zedthehedgehog

Since "ass" and "damn" have been removed, these should be removed too. They're not that bad. This also unintentionally censors "Bisexual".

2023-01-12 14:59 UTC, MikeDev101 requested changes

2023-01-12 14:59 UTC, MikeDev101 commented on better_profanity/profanity_wordlist.txt
>  shibari
ouch my search history

2023-01-12 15:00 UTC, MikeDev101 commented
Also, trying to clean up inactive branches

2023-01-28 01:00 UTC, JoshAtticus commented
> Since "ass" and "damn" have been removed, these should be removed too. They're not that bad. This also unintentionally censors "Bisexual".

Late but this is a bit more hardcore than ass or damn

2023-02-10 09:04 UTC, theotherhades commented
tbh sex and sexual are more likely to be used in a non-dirty context than ass, so if that's unblocked idk why sex and sexual shouldn't be

2023-02-10 09:12 UTC, tnix100 commented
Sexual should not be blocked imo, but then sex would probably need to be unblocked as well. As @theotherhades said, they're less likely to be used in a dirty context than ass.

2023-02-10 09:45 UTC, JoshAtticus commented
> Sexual should not be blocked imo, but then sex would probably need to be unblocked as well. As @theotherhades said, they're less likely to be used in a dirty context than ass.

Well then ass should be reblocked because no one uses ass to describe a donkey.

2023-02-10 19:24 UTC, MikeDev101 commented
> Well then ass should be reblocked because no one uses ass to describe a donkey.

Except for Shrek.

2023-02-24 23:07 UTC, mdwalters commented
shrek

2023-03-03 19:36 UTC, MikeDev101 commented
Closing because of going stale, and that we've modified things to move BF away from this repo.

2023-03-03 19:36 UTC, closed without merging