Add pr0n websites
meower-media-co/Meower-Server pull request #161
Opened 2023-02-18 03:24 UTC by zedthehedgehog

Add pr0n websites to the blocklist, nobody should link them

2023-02-18 03:25 UTC, williamhorning requested changes
removing the tlds would probably make filtering better

2023-02-18 03:28 UTC, williamhorning approved these changes

2023-02-18 05:02 UTC, showierdata9978 approved these changes

2023-02-19 02:09 UTC, MikeDev101 approved these changes

2023-02-19 02:09 UTC, merged