Feat: API for adding/removing whitelist/blacklisted words
meower-media-co/Meower-Server pull request #226
Opened 2024-02-23 01:11 UTC by showierdata9978

New Perm is CHANGE_PROFANITY (524288)

2024-02-23 05:09 UTC, tnix100 requested changes
Summarized from Discord.

- Modify the filter lists on the Supporter class rather than adding/removing words directly on better profanity.
- Add endpoint(s) to get current filter lists.

2024-02-28 17:13 UTC, showierdata9978 commented
bump

2024-03-01 17:31 UTC, MikeDev101 approved these changes

2024-03-03 04:28 UTC, tnix100 approved these changes
LGTM

2024-03-05 05:19 UTC, merged