api account creation and message reporting
meower-media-co/Meower-Server pull request #239
Opened 2024-06-25 15:45 UTC by williamhorning

this adds the following endpoints:
- /auth/register (gen_account in cl)
- /auth/login (authpswd)
- /posts/<post-id>/report (report)
- /users/<user-id>/report (report)

2024-06-25 15:52 UTC, NotFenixio commented
This is just awesome!

2024-06-26 03:25 UTC, tnix100 requested changes

2024-06-26 03:25 UTC, tnix100 commented on rest_api/auth.py
> +    print("test")
debug line, please remove

2024-06-26 03:25 UTC, tnix100 commented on rest_api/auth.py
> +
there used to be something around here that sent an inbox message if an account deletion was cancelled, that should be re-implemented here

2024-06-26 03:25 UTC, tnix100 commented on rest_api/users.py
> +    # Return updated relationshipFeat/api accounts
I don't think this comment change was intentional

2024-06-26 03:27 UTC, tnix100 commented on rest_api/auth.py
> +    print("test")
another debug line :p

2024-06-26 03:35 UTC, tnix100 approved these changes

2024-06-26 03:35 UTC, merged